### ISSUE TITLE
cv2 module not found

### ISSUE THREAD

**Issue by idkzyro** [karayaman/Play-online-chess-with-real-chess-board#14]
downloaded the opencv module, and still recieving this error

**Comment by karayaman** [comment]
Hi, I would suggest you to try the following:

1. Install the libraries and run the program as a superuser (sudo command for Linux).
2. Clone the repository using an IDE like PyCharm and follow the instructions there.
3. Create a virtual environment for this repository.
4. As far as I remember, I used opencv-python version 4.5.2.54 while preparing the latest release, so maybe you should try that one.

**Comment by idkzyro** [comment]
Hey thanks for the reply
I am using windows not linux
I have tried that version of opencv and it is still not working
I get 2 different errors, when using regular python:
```
Traceback (most recent call last):

  File "C:\Play-online-chess-with-real-chess-board-main\board_calibration.py", line 1, in <module>

    import cv2

Board calibration finished.
Traceback (most recent call last):

  File "C:\Play-online-chess-with-real-chess-board-main\main.py", line 2, in <module>

    import cv2

ModuleNotFoundError: No module named 'cv2'

Game finished.
```

And when using python 3.10

```
C:\Users\x\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe: can't open file 'C:\\WINDOWS\\system32\\board_calibration.py': [Errno 2] No such file or directory

Board calibration finished.
C:\Users\x\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe: can't open file 'C:\\WINDOWS\\system32\\main.py': [Errno 2] No such file or directory

Game finished.
```
