### ISSUE TITLE
AttributeError: '_thread._local' object has no attribute 'display'

### ISSUE THREAD

**Issue by fernandesafp** [karayaman/Play-online-chess-with-real-chess-board#25]
This happens once I either run main.py or start from the GUI.

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "commentator.py", line 22, in run
    resized_chessboard = self.game_state.get_chessboard()
  File "commentator.py", line 50, in get_chessboard
    img = np.array(np.array(self.sct.grab(monitor)))
  File ".env/lib/python3.10/site-packages/mss/base.py", line 90, in grab
    screenshot = self._grab_impl(monitor)
  File ".env/lib/python3.10/site-packages/mss/linux.py", line 428, in _grab_impl
    self._handles.display,
AttributeError: '_thread._local' object has no attribute 'display'
```

Anyone knows what this is about?

**Comment by SergioMOrozco** [comment]
Same issue here. Any resolution?

**Comment by karayaman** [comment]
Hi, the error has been fixed in the latest version.
